name: PowerPlugin
version: '${project.version}'
main: me.itzzdevk.powerplugin.PowerPlugin
api-version: '1.20'
authors:
  - ItzzDevk
  - RafalBerezin

commands:
  reroll:
    description: Reroll your Power!
    usage: /reroll
  power:
    description: Check your Power!
    usage: /power
  levels:
    description: Check your Power Level!
    usage: /levels
  level:
    description: Set the Specificied Players Level!
    usage: /level set <player> <amount>